apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheusrules.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: PrometheusRule
    listKind: PrometheusRuleList
    plural: prometheusrules
    singular: prometheusrule
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                groups:
                  type: array
                  items:
                    type: object
                    properties:
                      interval: { type: string }
                      name: { type: string }
                      partial_response_strategy: { type: string }
                      rules: { type: array, items: { type: object } }
                      selectors: { type: array, items: { type: object } }
